<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fluidcontent_zf4_grid"
 *
 * Auto generated by Extension Builder 2013-08-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Powermail: Zurb Foundation 4 Templates',
	'description' => '',
	'category' => 'misc',
	'author' => 'Jose Antonio Guerra',
	'author_email' => 'jaguerra@icti.es',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '2.0.13',
	'constraints' => array(
		'depends' => array(
			'powermail' => '2.0.13',
			'typo3' => '6.1.0-6.2.99',
			'vhs' => '1.8.0-1.8.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>